"""empty message

Revision ID: 3bd515d522d1
Revises: 612cf442e0b5
Create Date: 2026-03-02 00:05:58.438770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3bd515d522d1'
down_revision: Union[str, Sequence[str], None] = '612cf442e0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileencrypted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('encrypted_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fileencrypted', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fileencrypted_file_path'), ['file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_fileencrypted_uploaded_at'), ['uploaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fileencrypted', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fileencrypted_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_fileencrypted_file_path'))

    op.drop_table('fileencrypted')
    # ### end Alembic commands ###
