"""empty message

Revision ID: 612cf442e0b5
Revises: 53d276aa529b
Create Date: 2026-02-28 23:05:16.307983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '612cf442e0b5'
down_revision: Union[str, Sequence[str], None] = '53d276aa529b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_master_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('kdf_salt', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('kdf_salt')
        batch_op.drop_column('encrypted_master_key')

    # ### end Alembic commands ###
